[package]
name = "logical-verification"
version = "1.0"
lean_version = "leanprover-community/lean:3.20.0"
path = "."

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "d33341c90c18ef77d9df21b13951f4d0b2a0764a"}
